### ISSUE TITLE
remove loadTCA for typo3 7.x

### ISSUE THREAD

**Issue by s3zwirni** [dohomi/dd_googlesitemap_dmf#13]
Hi,

this extension use loadTCA in class.tx_ddgooglesitemap_dmf.php which causes an error in typo3 7.6. Removing this solves in my case the compatibility to this LTS-version.

Zwirni

**Comment by grimmcreative** [comment]
Look at https://github.com/dohomi/dd_googlesitemap_dmf/pull/14
Completely compatible now with 7 LTS

**Comment by dohomi** [comment]
I uploaded the file to the TER just now. Version 2.0.0 is now the PR for all versions > 6.2
