### ISSUE TITLE
Fatal Error after Installation

### ISSUE THREAD

**Issue by clemenskroell** [dohomi/dd_googlesitemap_dmf#8]
I get the following error after installing the extension:

Fatal error: Class 'tx_ddgooglesitemap_ttnews' not found in /srv/www/www.foo.bar/public_html/typo3conf/ext/dd_googlesitemap_dmf/class.tx_ddgooglesitemap_dmf.php on line 43

actually, i want to run it with tx_news and don't use tt_news. the manual says, that tx_news works out of the box?

any advice? thanks

**Comment by dohomi** [comment]
Hello,

it seems that there are recent changes of dd_googlesitemap where this project belongs. I haven't face this issue yet because I don't use TYPO3 7.x.

I'll see when I have the time to work on this, if it is urgent for you feel free to provide a pull request.

**Comment by clemenskroell** [comment]
Fyi: I'm using t3 6.2.12, not 7.x.

**Comment by dohomi** [comment]
Ok then it must be some recent changes at dd_googlesitemap itself. I will try to look into it asap

**Comment by clemenskroell** [comment]
any update on this?

**Comment by dohomi** [comment]
@clemenskroell I haven't faced the issue yet, so if you can provide a pull request I'm happy to merge it.

**Comment by dohomi** [comment]
@clemenskroell I uploaded a new version can you see if its fixed with 1.2.3?

**Comment by dohomi** [comment]
closing it now. feel free to reopen it
