### ISSUE TITLE
Not compatible with dd_googlesitemap 2.0

### ISSUE THREAD

**Issue by ste101** [dohomi/dd_googlesitemap_dmf#9]
I' getting this error:
```Fatal error: Class 'tx_ddgooglesitemap_ttnews' not found in /html/typo3/typo3conf/ext/dd_googlesitemap_dmf/class.tx_ddgooglesitemap_dmf.php on line 43```

**Comment by h3nn3s** [comment]
After a quick check I found a solution.
tx_ddgooglesitemap_dmf shoud extend DmitryDulepov\DdGooglesitemap\Generator\TtNewsSitemapGenerator instead of tx_ddgooglesitemap_ttnews

Dmitry moved his extension to namespaces in version 2

**Comment by dohomi** [comment]
@h3nn3s I uploaded a new version, should be available in the next 15min please check if it works now

**Comment by h3nn3s** [comment]
Jeb, looks good.

One hint: Now your Extension is only compatible with dd_googlesitemap > 2.0.0 and therefor only works with TYPO3 6.2

Some litte change with a huge impact

**Comment by dohomi** [comment]
Thanks I will update the README.

**Comment by rnakielski** [comment]
For us it works well with dd_googlesitemap 2.1.0 and TYPO3 7.6 
after changing the file class.ddgoooglesitemap_dmf.php:

class tx_ddgooglesitemap_dmf extends tx_ddgooglesitemap_ttnews { 
to
class tx_ddgooglesitemap_dmf extends DmitryDulepov\DdGooglesitemap\Generator\TtNewsSitemapGenerator{
as h3nn3s mentioned

and also a change from all t3lib_div::...
to 
\TYPO3\CMS\Core\Utility\GeneralUtility::

may be this helps somebody...

**Comment by dohomi** [comment]
Any PR is welcome. If anybody is interested in joining this project please send me a message. As I'm not working with a current TYPO3 version it is hard for me to maintain it.
